<?php
/* Autocomplete container */
$scriptUrl = $block->getScriptUrl();
$cssUrl = $block->getCssUrl();
$autocompleteCustomCss = $block->getAutocompleteCustomCss();
$searchPageCustomCss = $block->getSearchPageCustomCss();

//Current store's currency data
$currencyCode = $block->getCurrentCurrencyCode();
$currencyRate = $block->getCurrentCurrencyRate($currencyCode);
$baseCurrencyCode = $block->getBaseCurrencyCode();
$currencySymbol = $block->getCurrentCurrencySymbol($currencyCode);
?>

<script>
    window.st_currency = {
        currencyCode: "<?php echo $currencyCode; ?>",
        currencyRate: <?php echo $currencyRate; ?>,
        currencySymbol: "<?php echo $currencySymbol; ?>",
        baseCurrencyCode: "<?php echo $baseCurrencyCode; ?>"
    };

    window.st_update_minicart = function () {
        require(['Magento_Customer/js/customer-data'],
            function (customerData) {
                var sections = ['cart'];
                customerData.invalidate(sections);
                customerData.reload(sections, true);
            });
    }
</script>

<div id="st-autocomplete-container"></div>

<script type="text/javascript" src="<?php echo $scriptUrl ?>"></script>
<link href="<?php echo $cssUrl ?>" rel="stylesheet" type="text/css" media="all">

<style>
    <?php echo $autocompleteCustomCss; ?>
    <?php echo $searchPageCustomCss; ?>
</style>