<?php
/* Autocomplete container */
$scriptUrl = $block->getScriptUrl();
$cssUrl = $block->getCssUrl();
$autocompleteCustomCss = $block->getAutocompleteCustomCss();
$searchPageCustomCss = $block->getSearchPageCustomCss();

//Current store's currency data
$currencyCode = $block->getCurrentCurrencyCode();
$currencyRate = $block->getCurrentCurrencyRate($currencyCode);
$baseCurrencyCode = $block->getBaseCurrencyCode();
$currencySymbol = $block->getCurrentCurrencySymbol($currencyCode);
?>

<script>
    var st_currency = {
        currencyCode: <?php echo $currencyCode; ?>,
        currencyRate: <?php echo $currencyRate; ?>,
        currencySymbol: <?php echo $currencySymbol; ?>,
        baseCurrencyCode: <?php echo $baseCurrencyCode; ?>
    };
</script>

<div id="st-autocomplete-container"></div>

<script type="text/javascript" src="<?php echo $scriptUrl ?>"></script>
<link href="<?php echo $cssUrl?>" rel="stylesheet" type="text/css" media="all">

<style>
    <?php echo $autocompleteCustomCss; ?>
    <?php echo $searchPageCustomCss; ?>
</style>